Test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -109,6 +109,22 @@ jobs:
           passphrase: ${{ secrets.SSH_PASSPHRASE }}
           script: |
             cd foodgram
+            if [ ! -f .env ]; then
+              echo "POSTGRES_DB=foodgram" > .env
+              echo "POSTGRES_USER=foodgram_user" >> .env
+              echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
+              echo "DB_HOST=db" >> .env
+              echo "DB_PORT=5432" >> .env
+              echo "DB_TYPE=postgres" >> .env
+              echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
+              echo "DEBUG=False" >> .env
+              echo "ALLOWED_HOSTS=netkann.ru,localhost,127.0.0.1,158.160.71.90,foodgram_backend" >> .env
+            fi
+            # Проверка наличия .env
+            if [ ! -f .env ]; then
+              echo "Error: .env file not found!"
+              exit 1
+            fi
             sudo docker compose -f docker-compose.production.yml pull
             sudo docker compose -f docker-compose.production.yml down
             sudo docker compose -f docker-compose.production.yml up -d
